"""Property-based tests for TypeAnnotation unwrapping.

These tests supplement the parametrized tests in test_annotations.py by verifying
invariants (idempotence, base type recovery, qualifier and metadata accumulation)
over arbitrary nesting permutations generated by Hypothesis.
"""

from hypothesis import given

from sqlcrucible._types.annotations import TypeAnnotation, unwrap

from tests.strategies import BASE_TYPES, wrapped_type


@given(data=wrapped_type())
def test_unwrap_is_idempotent(data):
    annotation, _base, _qualifiers, _metadata = data

    first = unwrap(annotation)
    second = unwrap(first)
    assert first == second


@given(data=wrapped_type())
def test_unwrap_recovers_base_type(data):
    annotation, base, _qualifiers, _metadata = data

    result = unwrap(annotation)
    assert result == base


@given(data=wrapped_type())
def test_create_recovers_base_type(data):
    annotation, base, _qualifiers, _metadata = data

    result = TypeAnnotation.create(annotation)
    assert result.tp == base


@given(data=wrapped_type())
def test_create_collects_all_qualifiers(data):
    annotation, _base, expected_qualifiers, _metadata = data

    result = TypeAnnotation.create(annotation)
    assert result.qualifiers == expected_qualifiers


@given(data=wrapped_type())
def test_create_collects_all_metadata(data):
    annotation, _base, _qualifiers, expected_metadata = data

    result = TypeAnnotation.create(annotation)
    assert result.metadata == expected_metadata


@given(data=wrapped_type())
def test_create_is_idempotent(data):
    annotation, _base, _qualifiers, _metadata = data

    first = TypeAnnotation.create(annotation)
    second = TypeAnnotation.create(first.tp)
    assert second.tp == first.tp
    assert second.qualifiers == ()
    assert second.metadata == ()


@given(base=BASE_TYPES)
def test_plain_type_passes_through_unchanged(base):
    result = TypeAnnotation.create(base)
    assert result.tp == base
    assert result.qualifiers == ()
    assert result.metadata == ()


@given(base=BASE_TYPES)
def test_unwrap_plain_type_is_identity(base):
    result = unwrap(base)
    assert result == base
