"""Property-based tests for CachingConverter identity-map behaviour.

These tests supplement the hand-written tests in test_caching.py by verifying
identity-map invariants over randomly generated object graphs with controlled
sharing, generated by Hypothesis.
"""

from unittest.mock import MagicMock

from hypothesis import given

from sqlcrucible.conversion.caching import CachingConverter, _identity_map
from sqlcrucible.conversion.registry import Converter

from tests.strategies import Source, Target, shared_object_list


def _make_doubling_converter() -> tuple[CachingConverter[Source, Target], MagicMock]:
    """Build a CachingConverter wrapping a mock inner converter.

    Returns the caching converter and the mock so callers can inspect calls.
    """
    inner = MagicMock(spec=Converter)
    inner.convert.side_effect = lambda src: Target(value=src.value * 2)
    inner.safe_convert.side_effect = lambda src: Target(value=src.value * 2)
    return CachingConverter(inner), inner


@given(data=shared_object_list())
def test_same_object_returns_identical_result(data):
    reference_list, _unique_objects = data
    converter, _inner = _make_doubling_converter()

    with _identity_map():
        results = [converter.convert(src) for src in reference_list]

    seen: dict[int, Target] = {}
    for src, result in zip(reference_list, results, strict=True):
        if id(src) in seen:
            assert result is seen[id(src)]
        else:
            seen[id(src)] = result


@given(data=shared_object_list())
def test_inner_converter_called_once_per_unique_object(data):
    reference_list, unique_objects = data
    converter, inner = _make_doubling_converter()

    with _identity_map():
        for src in reference_list:
            converter.convert(src)

    unique_source_ids = {id(src) for src in reference_list}
    assert inner.convert.call_count == len(unique_source_ids)


@given(data=shared_object_list())
def test_safe_convert_same_identity_invariant(data):
    reference_list, _unique_objects = data
    converter, _inner = _make_doubling_converter()

    with _identity_map():
        results = [converter.safe_convert(src) for src in reference_list]

    seen: dict[int, Target] = {}
    for src, result in zip(reference_list, results, strict=True):
        if id(src) in seen:
            assert result is seen[id(src)]
        else:
            seen[id(src)] = result


@given(data=shared_object_list())
def test_separate_contexts_are_isolated(data):
    reference_list, _unique_objects = data
    converter, inner = _make_doubling_converter()

    with _identity_map():
        first_results = [converter.convert(src) for src in reference_list]

    inner.reset_mock()
    inner.convert.side_effect = lambda src: Target(value=src.value * 2)

    with _identity_map():
        second_results = [converter.convert(src) for src in reference_list]

    for first, second in zip(first_results, second_results, strict=True):
        assert first is not second

    unique_source_ids = {id(src) for src in reference_list}
    assert inner.convert.call_count == len(unique_source_ids)


@given(data=shared_object_list())
def test_conversion_results_are_correct(data):
    reference_list, _unique_objects = data
    converter, _inner = _make_doubling_converter()

    with _identity_map():
        results = [converter.convert(src) for src in reference_list]

    for src, result in zip(reference_list, results, strict=True):
        assert result.value == src.value * 2
