"""Tests for entity discovery utilities."""

from __future__ import annotations

import pytest

from sqlcrucible.stubs.discovery import get_entities_from_module, is_autogenerated

from tests.stubs.sample_models import (
    Animal,
    Dog,
    EntityWithExcludedField,
    RelationshipBase,
    SimpleTrack,
    StubAuthor,
    StubBook,
    StubTestBase,
)


def test_get_entities_finds_concrete_entities():
    entities = get_entities_from_module("tests.stubs.sample_models")
    entity_set = set(entities)
    assert {Animal, Dog, SimpleTrack, EntityWithExcludedField, StubAuthor, StubBook} <= entity_set


def test_get_entities_excludes_abstract():
    entities = get_entities_from_module("tests.stubs.sample_models")
    assert StubTestBase not in entities
    assert RelationshipBase not in entities


def test_get_entities_excludes_imported_types():
    from sqlcrucible.entity.core import SQLCrucibleBaseModel

    entities = get_entities_from_module("tests.stubs.sample_models")
    assert SQLCrucibleBaseModel not in entities


def test_get_entities_bad_module_raises():
    with pytest.raises(ModuleNotFoundError):
        get_entities_from_module("nonexistent.module.path")


def test_is_autogenerated_true():
    sa_type = SimpleTrack.__sqlalchemy_type__
    assert is_autogenerated(sa_type) is True


def test_is_autogenerated_false():
    assert is_autogenerated(SimpleTrack) is False
