"""Entity discovery utilities for stub generation."""

from __future__ import annotations

import importlib
from typing import Any

from sqlcrucible.entity.core import SQLCrucibleEntity


def get_entities_from_module(module_path: str) -> list[type[SQLCrucibleEntity]]:
    """Import a module and find all SQLCrucibleEntity subclasses.

    Args:
        module_path: Dotted module path (e.g., 'myapp.models')

    Returns:
        List of entity classes found in the module (excluding abstract entities).
    """
    module = importlib.import_module(module_path)
    entities = []

    for name in dir(module):
        obj = getattr(module, name)
        if (
            isinstance(obj, type)
            and issubclass(obj, SQLCrucibleEntity)
            and obj is not SQLCrucibleEntity
            and obj.__module__ == module_path
        ):
            # Skip abstract entities
            params = getattr(obj, "__sqlalchemy_params__", {})
            if params.get("__abstract__"):
                continue
            entities.append(obj)

    return entities


def is_autogenerated(cls: type[Any]) -> bool:
    """Check if a class is an autogenerated SQLAlchemy model from SQLCrucible."""
    return cls.__module__.startswith("sqlcrucible.generated.")
